// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/mydata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairAddress   string                 `protobuf:"bytes,1,opt,name=pair_address,json=pairAddress,proto3" json:"pair_address,omitempty"`
	Token0        string                 `protobuf:"bytes,2,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1        string                 `protobuf:"bytes,3,opt,name=token1,proto3" json:"token1,omitempty"`
	PriceUsd      float64                `protobuf:"fixed64,4,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	VolumeUsd     float64                `protobuf:"fixed64,5,opt,name=volume_usd,json=volumeUsd,proto3" json:"volume_usd,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_proto_mydata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mydata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_mydata_proto_rawDescGZIP(), []int{0}
}

func (x *PriceUpdate) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

func (x *PriceUpdate) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *PriceUpdate) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *PriceUpdate) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *PriceUpdate) GetVolumeUsd() float64 {
	if x != nil {
		return x.VolumeUsd
	}
	return 0
}

func (x *PriceUpdate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *PriceUpdate) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_mydata_proto protoreflect.FileDescriptor

const file_proto_mydata_proto_rawDesc = "" +
	"\n" +
	"\x12proto/mydata.proto\x12\tmydata.v1\"\xdd\x01\n" +
	"\vPriceUpdate\x12!\n" +
	"\fpair_address\x18\x01 \x01(\tR\vpairAddress\x12\x16\n" +
	"\x06token0\x18\x02 \x01(\tR\x06token0\x12\x16\n" +
	"\x06token1\x18\x03 \x01(\tR\x06token1\x12\x1b\n" +
	"\tprice_usd\x18\x04 \x01(\x01R\bpriceUsd\x12\x1d\n" +
	"\n" +
	"volume_usd\x18\x05 \x01(\x01R\tvolumeUsd\x12!\n" +
	"\fblock_number\x18\x06 \x01(\x04R\vblockNumber\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestampB8Z6github.com/Lazy-Parser/solana-substream/proto/pb/protob\x06proto3"

var (
	file_proto_mydata_proto_rawDescOnce sync.Once
	file_proto_mydata_proto_rawDescData []byte
)

func file_proto_mydata_proto_rawDescGZIP() []byte {
	file_proto_mydata_proto_rawDescOnce.Do(func() {
		file_proto_mydata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mydata_proto_rawDesc), len(file_proto_mydata_proto_rawDesc)))
	})
	return file_proto_mydata_proto_rawDescData
}

var file_proto_mydata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_mydata_proto_goTypes = []any{
	(*PriceUpdate)(nil), // 0: mydata.v1.PriceUpdate
}
var file_proto_mydata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mydata_proto_init() }
func file_proto_mydata_proto_init() {
	if File_proto_mydata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mydata_proto_rawDesc), len(file_proto_mydata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mydata_proto_goTypes,
		DependencyIndexes: file_proto_mydata_proto_depIdxs,
		MessageInfos:      file_proto_mydata_proto_msgTypes,
	}.Build()
	File_proto_mydata_proto = out.File
	file_proto_mydata_proto_goTypes = nil
	file_proto_mydata_proto_depIdxs = nil
}
