// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceUpdate {
    #[prost(string, tag="1")]
    pub pair_address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token0: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub token1: ::prost::alloc::string::String,
    #[prost(double, tag="4")]
    pub price_usd: f64,
    #[prost(double, tag="5")]
    pub volume_usd: f64,
    #[prost(uint64, tag="6")]
    pub block_number: u64,
    #[prost(uint64, tag="7")]
    pub timestamp: u64,
}
// @@protoc_insertion_point(module)
